import { ChannelListing, Review } from './types';

export const MOCK_CHANNELS: ChannelListing[] = [
  {
    id: '1',
    name: 'Tech Insights Pro',
    niche: 'Tech',
    subscribers: 45000,
    monetized: true,
    monthlyRevenue: 65000,
    askingPrice: 350000,
    description: 'A well-established tech review channel with high engagement in the US and UK markets. Consistent uploads for 2 years.',
    watchHours: 120000,
    imageUrl: 'https://picsum.photos/seed/rev3/800/500',
    contactEmail: 'seller1@example.com',
    growthData: [
      { month: 'Jan', subs: 40000 },
      { month: 'Feb', subs: 41500 },
      { month: 'Mar', subs: 43000 },
      { month: 'Apr', subs: 45000 },
    ],
    status: 'Available',
    listingId: 'YT-1001',
    creationDate: '2021-05-12',
    language: 'English',
    channelType: 'Tech Reviews',
    contentType: 'Original',
    realTimeViews: 1200,
    viewsLast28Days: 150000,
    lifetimeViews: 5000000,
    copyrightStrikes: 0,
    communityStrikes: 0,
    revenueLast28Days: 65000,
    lifetimeRevenue: 1800000
  },
  {
    id: '2',
    name: 'Gaming Galaxy',
    niche: 'Gaming',
    subscribers: 120000,
    monetized: true,
    monthlyRevenue: 150000,
    askingPrice: 850000,
    description: 'Massive gaming channel focused on Minecraft and Roblox. Highly active community and discord server included.',
    watchHours: 450000,
    imageUrl: 'https://picsum.photos/seed/gaming/800/450',
    contactEmail: 'seller2@example.com',
    growthData: [
      { month: 'Jan', subs: 100000 },
      { month: 'Feb', subs: 105000 },
      { month: 'Mar', subs: 112000 },
      { month: 'Apr', subs: 120000 },
    ],
    status: 'Available',
    listingId: 'YT-1002',
    creationDate: '2019-11-20',
    language: 'English',
    channelType: 'Gaming',
    contentType: 'Original',
    realTimeViews: 5000,
    viewsLast28Days: 1200000,
    lifetimeViews: 45000000,
    copyrightStrikes: 0,
    communityStrikes: 0,
    revenueLast28Days: 150000,
    lifetimeRevenue: 9500000
  },
  {
    id: '3',
    name: 'Finance Freedom',
    niche: 'Finance',
    subscribers: 15000,
    monetized: true,
    monthlyRevenue: 95000,
    askingPrice: 550000,
    description: 'High CPM channel focused on stock market analysis and personal finance. Audience is primarily professionals.',
    watchHours: 45000,
    imageUrl: 'https://picsum.photos/seed/finance/800/450',
    contactEmail: 'seller3@example.com',
    growthData: [
      { month: 'Jan', subs: 12000 },
      { month: 'Feb', subs: 13000 },
      { month: 'Mar', subs: 14000 },
      { month: 'Apr', subs: 15000 },
    ],
    status: 'Available',
    listingId: 'YT-1003',
    creationDate: '2022-01-15',
    language: 'English',
    channelType: 'Finance',
    contentType: 'Original',
    realTimeViews: 800,
    viewsLast28Days: 80000,
    lifetimeViews: 1200000,
    copyrightStrikes: 0,
    communityStrikes: 0,
    revenueLast28Days: 95000,
    lifetimeRevenue: 1200000
  },
  {
    id: '4',
    name: 'Daily Vlog Life',
    niche: 'Vlog',
    subscribers: 8500,
    monetized: false,
    askingPrice: 65000,
    description: 'Personal vlog channel with a loyal following. Great for someone looking to start their own vlog journey.',
    watchHours: 3200,
    imageUrl: 'https://picsum.photos/seed/vlog/800/450',
    contactEmail: 'seller4@example.com',
    growthData: [
      { month: 'Jan', subs: 7000 },
      { month: 'Feb', subs: 7500 },
      { month: 'Mar', subs: 8000 },
      { month: 'Apr', subs: 8500 },
    ],
    status: 'Sold',
    listingId: 'YT-1004',
    creationDate: '2023-05-10',
    language: 'Hindi',
    channelType: 'Vlog',
    contentType: 'Original',
    realTimeViews: 150,
    viewsLast28Days: 12000,
    lifetimeViews: 150000,
    copyrightStrikes: 0,
    communityStrikes: 0,
    revenueLast28Days: 0,
    lifetimeRevenue: 0
  }
];

export const MOCK_IMAGE_REVIEWS = [
  'https://picsum.photos/seed/rev1/800/500',
  'https://picsum.photos/seed/rev2/800/500',
  'https://picsum.photos/seed/rev3/800/500',
  'https://picsum.photos/seed/rev4/800/500',
  'https://picsum.photos/seed/rev5/800/500',
];
